version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: itemdb
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: f30ds51f0sdf43aa40aw3001asd105331ws6d1as5d013s
    volumes:
      - ./mongo-volumes:/data/db
    ports:
      - '27017-27019:27017-27019'